// Auto-generated by scripts/gen-svgs-index.js
// Do not edit manually

import Svg0 from './哔哩哔哩.svg'
import Svg1 from './小红书.svg'
import Svg2 from './知乎.svg'
import Svg3 from './dots.svg'
import Svg4 from './dragger.svg'
import Svg5 from './email.svg'
import Svg6 from './facebook.svg'
import Svg7 from './github.svg'
import Svg8 from './instagram.svg'
import Svg9 from './pen.svg'
import Svg10 from './pictures.svg'
import Svg11 from './qq.svg'
import Svg12 from './scroll-filled.svg'
import Svg13 from './scroll-outline.svg'
import Svg14 from './short-line.svg'
import Svg15 from './tg.svg'
import Svg16 from './tiktok.svg'
import Svg17 from './top.svg'
import Svg18 from './wechat.svg'
import Svg19 from './weibo.svg'
import Svg20 from './x.svg'

export type SvgComponent = React.ComponentType<React.SVGProps<SVGSVGElement>>

export const svgItems: { key: string; Component: SvgComponent }[] = [
	{ key: './哔哩哔哩.svg', Component: Svg0 },
	{ key: './小红书.svg', Component: Svg1 },
	{ key: './知乎.svg', Component: Svg2 },
	{ key: './dots.svg', Component: Svg3 },
	{ key: './dragger.svg', Component: Svg4 },
	{ key: './email.svg', Component: Svg5 },
	{ key: './facebook.svg', Component: Svg6 },
	{ key: './github.svg', Component: Svg7 },
	{ key: './instagram.svg', Component: Svg8 },
	{ key: './pen.svg', Component: Svg9 },
	{ key: './pictures.svg', Component: Svg10 },
	{ key: './qq.svg', Component: Svg11 },
	{ key: './scroll-filled.svg', Component: Svg12 },
	{ key: './scroll-outline.svg', Component: Svg13 },
	{ key: './short-line.svg', Component: Svg14 },
	{ key: './tg.svg', Component: Svg15 },
	{ key: './tiktok.svg', Component: Svg16 },
	{ key: './top.svg', Component: Svg17 },
	{ key: './wechat.svg', Component: Svg18 },
	{ key: './weibo.svg', Component: Svg19 },
	{ key: './x.svg', Component: Svg20 }
]
